[mypy]
python_version = 3.12
mypy_path = server
explicit_package_bases = True
ignore_missing_imports = False
plugins = pydantic.mypy

[mypy-jose.*]
ignore_missing_imports = True

[mypy-passlib.*]
ignore_missing_imports = True

[mypy-testcontainers.*]
ignore_missing_imports = True

[mypy-apscheduler.*]
ignore_missing_imports = True

[mypy-openpyxl.*]
ignore_missing_imports = True

[mypy-reportlab.*]
ignore_missing_imports = True

[mypy-factory.*]
ignore_missing_imports = True
